#ifndef GCONTROLLERINPUTDEFINES_H
#define GCONTROLLERINPUTDEFINES_H

/*!
File: GControllerCodes.h
Purpose: The Gateware controller input codes
Author: Devin Wright
Contributors: N/A
Last Modified: 11/29/2018
Copyright: 7thGate Software LLC.
License: MIT
*/

// Example Input code: 0XFF01112 FF(Reserved for future use) 01(Controler ID) 1(Axis || Button) 12(Input type)

// Controller IDs
#define G_GENERAL_CONTROLLER			0x00000 //! No max controller count
#define G_XBOX_CONTROLLER				0x01000 //! Supports up to four controllers
#define G_PS4_CONTROLLER				0x02000 //! No max controller count

// Input type
#define G_SOUTH_BTN						0x00
#define G_EAST_BTN						0x01
#define G_NORTH_BTN						0x02
#define G_WEST_BTN						0x03
#define G_LEFT_SHOULDER_BTN				0x04
#define G_RIGHT_SHOULDER_BTN			0x05
#define G_LEFT_TRIGGER_AXIS				0x06
#define G_RIGHT_TRIGGER_AXIS			0x07
#define G_DPAD_LEFT_BTN					0x08
#define G_DPAD_RIGHT_BTN				0x09
#define G_DPAD_UP_BTN					0x0A
#define G_DPAD_DOWN_BTN					0x0B
#define G_LEFT_THUMB_BTN				0x0C
#define G_RIGHT_THUMB_BTN				0x0D
#define G_START_BTN						0x0E
#define G_SELECT_BTN					0x0F
#define G_LX_AXIS						0x10
#define G_LY_AXIS						0x11
#define G_RX_AXIS						0x12
#define G_RY_AXIS						0x13

// Axis || Button
#define G_BUTTON						0x0
#define G_AXIS							0x1


////Input codes
// General Controller
#define G_GENERAL_SOUTH_BTN				((G_GENERAL_CONTROLLER) | 0xFF00000)
#define G_GENERAL_EAST_BTN				((G_GENERAL_CONTROLLER) | 0xFF00001)
#define G_GENERAL_NORTH_BTN				((G_GENERAL_CONTROLLER) | 0xFF00002)
#define G_GENERAL_WEST_BTN				((G_GENERAL_CONTROLLER) | 0xFF00003)
#define G_GENERAL_LEFT_SHOULDER_BTN		((G_GENERAL_CONTROLLER) | 0xFF00004)
#define G_GENERAL_RIGHT_SHOULDER_BTN    ((G_GENERAL_CONTROLLER) | 0xFF00005)
#define G_GENERAL_LEFT_TRIGGER_AXIS	    ((G_GENERAL_CONTROLLER) | 0xFF00106)
#define G_GENERAL_RIGHT_TRIGGER_AXIS    ((G_GENERAL_CONTROLLER) | 0xFF00107)
#define G_GENERAL_DPAD_LEFT_BTN			((G_GENERAL_CONTROLLER) | 0xFF00008)
#define G_GENERAL_DPAD_RIGHT_BTN		((G_GENERAL_CONTROLLER) | 0xFF00009)
#define G_GENERAL_DPAD_UP_BTN			((G_GENERAL_CONTROLLER) | 0xFF0000A)
#define G_GENERAL_DPAD_DOWN_BTN			((G_GENERAL_CONTROLLER) | 0xFF0000B)
#define G_GENERAL_LEFT_THUMB_BTN		((G_GENERAL_CONTROLLER) | 0xFF0000C)
#define G_GENERAL_RIGHT_THUMB_BTN		((G_GENERAL_CONTROLLER) | 0xFF0000D)
#define G_GENERAL_START_BTN				((G_GENERAL_CONTROLLER) | 0xFF0000E)
#define G_GENERAL_SELECT_BTN			((G_GENERAL_CONTROLLER) | 0xFF0000F)
#define G_GENERAL_LX_AXIS				((G_GENERAL_CONTROLLER) | 0xFF00110)
#define G_GENERAL_LY_AXIS				((G_GENERAL_CONTROLLER) | 0xFF00111)
#define G_GENERAL_RX_AXIS				((G_GENERAL_CONTROLLER) | 0xFF00112)
#define G_GENERAL_RY_AXIS				((G_GENERAL_CONTROLLER) | 0xFF00113)

// Xbox Controller
#define G_XBOX_A_BTN					((G_XBOX_CONTROLLER) | 0xFF00000)
#define G_XBOX_B_BTN					((G_XBOX_CONTROLLER) | 0xFF00001)
#define G_XBOX_Y_BTN					((G_XBOX_CONTROLLER) | 0xFF00002)
#define G_XBOX_X_BTN					((G_XBOX_CONTROLLER) | 0xFF00003)
#define G_XBOX_LEFT_SHOULDER_BTN		((G_XBOX_CONTROLLER) | 0xFF00004)
#define G_XBOX_RIGHT_SHOULDER_BTN		((G_XBOX_CONTROLLER) | 0xFF00005)
#define G_XBOX_LEFT_TRIGGER_AXIS		((G_XBOX_CONTROLLER) | 0xFF00106)
#define G_XBOX_RIGHT_TRIGGER_AXIS		((G_XBOX_CONTROLLER) | 0xFF00107)
#define G_XBOX_DPAD_LEFT_BTN			((G_XBOX_CONTROLLER) | 0xFF00008)
#define G_XBOX_DPAD_RIGHT_BTN			((G_XBOX_CONTROLLER) | 0xFF00009)
#define G_XBOX_DPAD_UP_BTN				((G_XBOX_CONTROLLER) | 0xFF0000A)
#define G_XBOX_DPAD_DOWN_BTN			((G_XBOX_CONTROLLER) | 0xFF0000B)
#define G_XBOX_LEFT_THUMB_BTN			((G_XBOX_CONTROLLER) | 0xFF0000C)
#define G_XBOX_RIGHT_THUMB_BTN			((G_XBOX_CONTROLLER) | 0xFF0000D)
#define G_XBOX_START_BTN				((G_XBOX_CONTROLLER) | 0xFF0000E)
#define G_XBOX_BACK_BTN					((G_XBOX_CONTROLLER) | 0xFF0000F)
#define G_XBOX_LX_AXIS					((G_XBOX_CONTROLLER) | 0xFF00110)
#define G_XBOX_LY_AXIS					((G_XBOX_CONTROLLER) | 0xFF00111)
#define G_XBOX_RX_AXIS					((G_XBOX_CONTROLLER) | 0xFF00112)
#define G_XBOX_RY_AXIS					((G_XBOX_CONTROLLER) | 0xFF00113)

// PS4 Controller
#define G_PS4_X_BTN						((G_PS4_CONTROLLER) | 0xFF00000) 
#define G_PS4_CIRCLE_BTN				((G_PS4_CONTROLLER) | 0xFF00001)
#define G_PS4_TRIANGLE_BTN				((G_PS4_CONTROLLER) | 0xFF00002)
#define G_PS4_SQUARE_BTN				((G_PS4_CONTROLLER) | 0xFF00003)
#define G_PS4_LEFT_SHOULDER_BTN			((G_PS4_CONTROLLER) | 0xFF00004)
#define G_PS4_RIGHT_SHOULDER_BTN	    ((G_PS4_CONTROLLER) | 0xFF00005)
#define G_PS4_LEFT_TRIGGER_AXIS			((G_PS4_CONTROLLER) | 0xFF00106)
#define G_PS4_RIGHT_TRIGGER_AXIS		((G_PS4_CONTROLLER) | 0xFF00107)
#define G_PS4_DPAD_LEFT_BTN				((G_PS4_CONTROLLER) | 0xFF00008)
#define G_PS4_DPAD_RIGHT_BTN			((G_PS4_CONTROLLER) | 0xFF00009)
#define G_PS4_DPAD_UP_BTN				((G_PS4_CONTROLLER) | 0xFF0000A)
#define G_PS4_DPAD_DOWN_BTN				((G_PS4_CONTROLLER) | 0xFF0000B)
#define G_PS4_LEFT_THUMB_BTN			((G_PS4_CONTROLLER) | 0xFF0000C)
#define G_PS4_RIGHT_THUMB_BTN			((G_PS4_CONTROLLER) | 0xFF0000D)
#define G_PS4_START_BTN					((G_PS4_CONTROLLER) | 0xFF0000E)
#define G_PS4_BACK_BTN					((G_PS4_CONTROLLER) | 0xFF0000F)
#define G_PS4_LX_AXIS					((G_PS4_CONTROLLER) | 0xFF00110)
#define G_PS4_LY_AXIS					((G_PS4_CONTROLLER) | 0xFF00111)
#define G_PS4_RX_AXIS					((G_PS4_CONTROLLER) | 0xFF00112)
#define G_PS4_RY_AXIS					((G_PS4_CONTROLLER) | 0xFF00113)

#endif 