//#import "../../../../Source/G_System/G_Core/UnitTestMain.cpp"
#import "../UnitTestMain.cpp"
#import "../G_System/GBufferedInputTests.cpp"
#import "../G_System/GInputTests.cpp"
#import "../G_System/GFileTest.cpp"
#import "../G_System/GLogTest.cpp"
#import "../G_System/GWindowTests.cpp"
#import "../G_Audio/GAudioTests.cpp" // Audio system seems to have some entitlment issues onMojave but it does pass all tests
#import "../G_System/GControllerTest.cpp"
#import "../G_System/GBufferedInputTestListener.cpp"
#import "../G_System/GWindowTestListener.cpp"
#import "../G_System/GControllerTestListener.cpp"
//#import "../G_Graphics/GOpenGLSurfaceTest.cpp"
#import "../G_Math/GMatrixTest.cpp"
#import "../G_Math/GQuaternionTest.cpp"
#import "../G_Math/GVectorTest.cpp"
#import "../Common.cpp"
