var annotated_dup =
[
    [ "Catch", null, [
      [ "Detail", null, [
        [ "Approx", "classCatch_1_1Detail_1_1Approx.html", "classCatch_1_1Detail_1_1Approx" ],
        [ "BorgType", "structCatch_1_1Detail_1_1BorgType.html", "structCatch_1_1Detail_1_1BorgType" ],
        [ "FalseType", "structCatch_1_1Detail_1_1FalseType.html", "structCatch_1_1Detail_1_1FalseType" ],
        [ "IsStreamInsertable", "structCatch_1_1Detail_1_1IsStreamInsertable.html", "structCatch_1_1Detail_1_1IsStreamInsertable" ],
        [ "StringMakerBase", "structCatch_1_1Detail_1_1StringMakerBase.html", null ],
        [ "StringMakerBase< true >", "structCatch_1_1Detail_1_1StringMakerBase_3_01true_01_4.html", null ],
        [ "TrueType", "structCatch_1_1Detail_1_1TrueType.html", "structCatch_1_1Detail_1_1TrueType" ]
      ] ],
      [ "Internal", null, [
        [ "Evaluator", "classCatch_1_1Internal_1_1Evaluator.html", null ],
        [ "Evaluator< T1, T2, IsEqualTo >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsEqualTo_01_4.html", null ],
        [ "Evaluator< T1, T2, IsGreaterThan >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsGreaterThan_01_4.html", null ],
        [ "Evaluator< T1, T2, IsGreaterThanOrEqualTo >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsGreaterThanOrEqualTo_01_4.html", null ],
        [ "Evaluator< T1, T2, IsLessThan >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsLessThan_01_4.html", null ],
        [ "Evaluator< T1, T2, IsLessThanOrEqualTo >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsLessThanOrEqualTo_01_4.html", null ],
        [ "Evaluator< T1, T2, IsNotEqualTo >", "structCatch_1_1Internal_1_1Evaluator_3_01T1_00_01T2_00_01IsNotEqualTo_01_4.html", null ],
        [ "OperatorTraits", "structCatch_1_1Internal_1_1OperatorTraits.html", null ],
        [ "OperatorTraits< IsEqualTo >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsEqualTo_01_4.html", null ],
        [ "OperatorTraits< IsGreaterThan >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsGreaterThan_01_4.html", null ],
        [ "OperatorTraits< IsGreaterThanOrEqualTo >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsGreaterThanOrEqualTo_01_4.html", null ],
        [ "OperatorTraits< IsLessThan >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsLessThan_01_4.html", null ],
        [ "OperatorTraits< IsLessThanOrEqualTo >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsLessThanOrEqualTo_01_4.html", null ],
        [ "OperatorTraits< IsNotEqualTo >", "structCatch_1_1Internal_1_1OperatorTraits_3_01IsNotEqualTo_01_4.html", null ]
      ] ],
      [ "Matchers", null, [
        [ "Impl", null, [
          [ "Generic", null, [
            [ "AllOf", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1AllOf.html", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1AllOf" ],
            [ "AnyOf", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1AnyOf.html", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1AnyOf" ],
            [ "Not", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1Not.html", "classCatch_1_1Matchers_1_1Impl_1_1Generic_1_1Not" ]
          ] ],
          [ "StdString", null, [
            [ "CasedString", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1CasedString.html", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1CasedString" ],
            [ "Contains", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1Contains.html", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1Contains" ],
            [ "EndsWith", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1EndsWith.html", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1EndsWith" ],
            [ "Equals", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1Equals.html", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1Equals" ],
            [ "StartsWith", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1StartsWith.html", "structCatch_1_1Matchers_1_1Impl_1_1StdString_1_1StartsWith" ]
          ] ],
          [ "Matcher", "structCatch_1_1Matchers_1_1Impl_1_1Matcher.html", "structCatch_1_1Matchers_1_1Impl_1_1Matcher" ],
          [ "MatcherImpl", "structCatch_1_1Matchers_1_1Impl_1_1MatcherImpl.html", "structCatch_1_1Matchers_1_1Impl_1_1MatcherImpl" ]
        ] ]
      ] ],
      [ "AssertionInfo", "structCatch_1_1AssertionInfo.html", "structCatch_1_1AssertionInfo" ],
      [ "AssertionResult", "classCatch_1_1AssertionResult.html", "classCatch_1_1AssertionResult" ],
      [ "AssertionResultData", "structCatch_1_1AssertionResultData.html", "structCatch_1_1AssertionResultData" ],
      [ "AutoReg", "structCatch_1_1AutoReg.html", "structCatch_1_1AutoReg" ],
      [ "BetweenGenerator", "classCatch_1_1BetweenGenerator.html", "classCatch_1_1BetweenGenerator" ],
      [ "CaseSensitive", "structCatch_1_1CaseSensitive.html", "structCatch_1_1CaseSensitive" ],
      [ "CompositeGenerator", "classCatch_1_1CompositeGenerator.html", "classCatch_1_1CompositeGenerator" ],
      [ "CopyableStream", "structCatch_1_1CopyableStream.html", "structCatch_1_1CopyableStream" ],
      [ "Counts", "structCatch_1_1Counts.html", "structCatch_1_1Counts" ],
      [ "ExceptionTranslatorRegistrar", "classCatch_1_1ExceptionTranslatorRegistrar.html", "classCatch_1_1ExceptionTranslatorRegistrar" ],
      [ "ExpressionLhs", "classCatch_1_1ExpressionLhs.html", "classCatch_1_1ExpressionLhs" ],
      [ "IContext", "structCatch_1_1IContext.html", "structCatch_1_1IContext" ],
      [ "IExceptionTranslator", "structCatch_1_1IExceptionTranslator.html", "structCatch_1_1IExceptionTranslator" ],
      [ "IExceptionTranslatorRegistry", "structCatch_1_1IExceptionTranslatorRegistry.html", "structCatch_1_1IExceptionTranslatorRegistry" ],
      [ "IGenerator", "structCatch_1_1IGenerator.html", "structCatch_1_1IGenerator" ],
      [ "IGeneratorInfo", "structCatch_1_1IGeneratorInfo.html", "structCatch_1_1IGeneratorInfo" ],
      [ "IGeneratorsForTest", "structCatch_1_1IGeneratorsForTest.html", "structCatch_1_1IGeneratorsForTest" ],
      [ "IMutableContext", "structCatch_1_1IMutableContext.html", "structCatch_1_1IMutableContext" ],
      [ "IMutableRegistryHub", "structCatch_1_1IMutableRegistryHub.html", "structCatch_1_1IMutableRegistryHub" ],
      [ "IRegistryHub", "structCatch_1_1IRegistryHub.html", "structCatch_1_1IRegistryHub" ],
      [ "IResultCapture", "structCatch_1_1IResultCapture.html", "structCatch_1_1IResultCapture" ],
      [ "IRunner", "structCatch_1_1IRunner.html", "structCatch_1_1IRunner" ],
      [ "IShared", "structCatch_1_1IShared.html", "structCatch_1_1IShared" ],
      [ "ITagAliasRegistry", "structCatch_1_1ITagAliasRegistry.html", "structCatch_1_1ITagAliasRegistry" ],
      [ "ITestCase", "structCatch_1_1ITestCase.html", "structCatch_1_1ITestCase" ],
      [ "ITestCaseRegistry", "structCatch_1_1ITestCaseRegistry.html", "structCatch_1_1ITestCaseRegistry" ],
      [ "MessageBuilder", "structCatch_1_1MessageBuilder.html", "structCatch_1_1MessageBuilder" ],
      [ "MessageInfo", "structCatch_1_1MessageInfo.html", "structCatch_1_1MessageInfo" ],
      [ "MethodTestCase", "classCatch_1_1MethodTestCase.html", "classCatch_1_1MethodTestCase" ],
      [ "NameAndDesc", "structCatch_1_1NameAndDesc.html", "structCatch_1_1NameAndDesc" ],
      [ "NonCopyable", "classCatch_1_1NonCopyable.html", "classCatch_1_1NonCopyable" ],
      [ "NotImplementedException", "classCatch_1_1NotImplementedException.html", "classCatch_1_1NotImplementedException" ],
      [ "Option", "classCatch_1_1Option.html", "classCatch_1_1Option" ],
      [ "pluralise", "structCatch_1_1pluralise.html", "structCatch_1_1pluralise" ],
      [ "Ptr", "classCatch_1_1Ptr.html", "classCatch_1_1Ptr" ],
      [ "RegistrarForTagAliases", "structCatch_1_1RegistrarForTagAliases.html", "structCatch_1_1RegistrarForTagAliases" ],
      [ "ResultBuilder", "classCatch_1_1ResultBuilder.html", "classCatch_1_1ResultBuilder" ],
      [ "ResultDisposition", "structCatch_1_1ResultDisposition.html", "structCatch_1_1ResultDisposition" ],
      [ "ResultWas", "structCatch_1_1ResultWas.html", "structCatch_1_1ResultWas" ],
      [ "SafeBool", "classCatch_1_1SafeBool.html", "classCatch_1_1SafeBool" ],
      [ "ScopedMessage", "classCatch_1_1ScopedMessage.html", "classCatch_1_1ScopedMessage" ],
      [ "Section", "classCatch_1_1Section.html", "classCatch_1_1Section" ],
      [ "SectionEndInfo", "structCatch_1_1SectionEndInfo.html", "structCatch_1_1SectionEndInfo" ],
      [ "SectionInfo", "structCatch_1_1SectionInfo.html", "structCatch_1_1SectionInfo" ],
      [ "SharedImpl", "structCatch_1_1SharedImpl.html", "structCatch_1_1SharedImpl" ],
      [ "SourceLineInfo", "structCatch_1_1SourceLineInfo.html", "structCatch_1_1SourceLineInfo" ],
      [ "StreamEndStop", "structCatch_1_1StreamEndStop.html", "structCatch_1_1StreamEndStop" ],
      [ "StringMaker", "structCatch_1_1StringMaker.html", null ],
      [ "StringMaker< R C::* >", "structCatch_1_1StringMaker_3_01R_01C_1_1_5_01_4.html", null ],
      [ "StringMaker< T * >", "structCatch_1_1StringMaker_3_01T_01_5_01_4.html", null ],
      [ "TagAlias", "structCatch_1_1TagAlias.html", "structCatch_1_1TagAlias" ],
      [ "TestCase", "classCatch_1_1TestCase.html", "classCatch_1_1TestCase" ],
      [ "TestCaseInfo", "structCatch_1_1TestCaseInfo.html", "structCatch_1_1TestCaseInfo" ],
      [ "TestFailureException", "structCatch_1_1TestFailureException.html", null ],
      [ "Timer", "classCatch_1_1Timer.html", "classCatch_1_1Timer" ],
      [ "Totals", "structCatch_1_1Totals.html", "structCatch_1_1Totals" ],
      [ "ValuesGenerator", "classCatch_1_1ValuesGenerator.html", "classCatch_1_1ValuesGenerator" ]
    ] ],
    [ "GW", "namespaceGW.html", "namespaceGW" ],
    [ "_WDIR", "struct__WDIR.html", "struct__WDIR" ],
    [ "_wdirent", "struct__wdirent.html", "struct__wdirent" ],
    [ "AppWindow", "classAppWindow.html", "classAppWindow" ],
    [ "BufferedInput", "classBufferedInput.html", "classBufferedInput" ],
    [ "DIR", "structDIR.html", "structDIR" ],
    [ "dirent", "structdirent.html", "structdirent" ],
    [ "FileIO", "classFileIO.html", "classFileIO" ],
    [ "GBufferedInputTestListener", "classGBufferedInputTestListener.html", "classGBufferedInputTestListener" ],
    [ "GIResponder", "interfaceGIResponder.html", "interfaceGIResponder" ],
    [ "GResponder", "interfaceGResponder.html", "interfaceGResponder" ],
    [ "GWAppDelegate", "interfaceGWAppDelegate.html", "interfaceGWAppDelegate" ],
    [ "GWDelegate", "interfaceGWDelegate.html", "interfaceGWDelegate" ],
    [ "GWindowTestListener", "classGWindowTestListener.html", "classGWindowTestListener" ],
    [ "GWMacWindow", "interfaceGWMacWindow.html", null ],
    [ "GWResponder", "interfaceGWResponder.html", "interfaceGWResponder" ],
    [ "Input", "classInput.html", "classInput" ],
    [ "LogFile", "classLogFile.html", "classLogFile" ],
    [ "TestListener", "classTestListener.html", "classTestListener" ]
];