#ifndef GCONTROLLER_STATIC_H
#define GCONTROLLER_STATIC_H
#include "../../Interface/G_System/GControllerInputDefines.h"

static const unsigned int Mac_ControllerCodes[][3] = {
	  //Genenral      //Xbox		   //PS4
	{ G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 0
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_WEST_BTN}, // 1
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_SOUTH_BTN}, // 2
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_EAST_BTN}, // 3
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_NORTH_BTN}, // 4
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_LEFT_SHOULDER_BTN}, // 5
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_RIGHT_SHOULDER_BTN}, // 6
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 7
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 8
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_SELECT_BTN}, // 9
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_START_BTN}, // 10
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_LEFT_THUMB_BTN}, // 11
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_RIGHT_THUMB_BTN}, // 12
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 13
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 14
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 15
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 16
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 17
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 18
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 19
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 20
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 21
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 22
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 23
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 24
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 25
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 26
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 27
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 28
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 29
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 30
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 31
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 32
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 33
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 34
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 35
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 36
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 37
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 38
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 39
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 40
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 41
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 42
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 43
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 44
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 45
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 46
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 47
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_LX_AXIS}, // 48
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_LY_AXIS}, // 49
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_RX_AXIS}, // 50
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_LEFT_TRIGGER_AXIS}, // 51
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_RIGHT_TRIGGER_AXIS}, // 52
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_RY_AXIS}, // 53
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 54
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 55
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 56
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 57
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 58
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 59
    { G_UNKOWN_INPUT,  G_UNKOWN_INPUT,  G_UNKOWN_INPUT}, // 60
};

#endif
